/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2025-08-15

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f429i_discovery.h"
#include "stm32f429i_discovery_lcd.h"
#include "tm_stm32f4_stmpe811.h"
#include "tm_stm32f4_disco.h"
#include "tm_stm32f4_ili9341_button.h"
#include "tm_stm32f4_fonts.h"
#include "tm_stm32f4_ili9341.h"
#include "stm32f4xx_adc.h"
#include "stm32f4xx_dma.h"
#include "stm32f4xx_tim.h"
#include "tm_stm32f4_spi.h"
#include "tm_stm32f4_spi_dma.h"
#include "tm_stm32f4_fonts.h"
#include "misc.h"
#include "button_back.h"
#include "defines.h"
#include "dht22.h"
#include "fsmc_nand.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

/* Capacitance */
#define RESISTOR        10000.0f      // 10kΩ resistor
#define CAP_CTRL_PIN    GPIO_Pin_6    // PA6 → charge/discharge control
#define CAP_ADC_PIN     GPIO_Pin_7    // PA7 → ADC input for voltage measurement
#define ADC_CHANNEL     ADC_Channel_7 // PA7 is channel 7 for ADC
#define ADC_MAX         4095.0f
#define V_THRESHOLD     2.1f          // Voltage threshold (63% of 3.3V)
#define ADC_THRESHOLD_COUNT ((uint16_t)((V_THRESHOLD / 3.3f) * ADC_MAX))
#define TIMEOUT_US      5000000u      // 5s timeout
#define DISCHARGE_SETTLE_US 2000u     // Discharge settling time

typedef enum {
    CAP_STATE_DISCHARGED = 0,
    CAP_STATE_CHARGING,
    CAP_STATE_MEASURED
} CapState_t;

/* Resistance */
#define R1 10000.0f
#define R2 10000.0f
#define R3 10000.0f
#define VS 3.3f

/* Grid and Display Parameters */
#define HORIZ_DIV 6
#define VERT_DIV 4
#define PIXELS_PER_DIV_H 45
#define PIXELS_PER_DIV_V 43
#define SAMPLES_PER_DIV 45
#define BUFFER_SIZE (HORIZ_DIV * SAMPLES_PER_DIV * 2) // Dual channel
#define MAX_POINTS (BUFFER_SIZE / 2)

/* Display dimensions */
#define LCD_WIDTH 320
#define LCD_HEIGHT 240
#define GRID_X 0
#define GRID_Y 30
#define GRID_WIDTH (HORIZ_DIV * PIXELS_PER_DIV_H)  // 270 pixels (6*45)
#define GRID_HEIGHT (VERT_DIV * PIXELS_PER_DIV_V)  // 172 pixels (4*43)

/* Button areas */
#define BOTTOM_BUTTON_HEIGHT 40
#define RIGHT_BUTTON_WIDTH 50

/* Save waveform */
#define NAND_PAGE_SIZE ((uint16_t)0x0800) /* 2 * 1024 bytes per page */

/* DMM Display Area */
#define DMM_DISPLAY_X 5
#define DMM_DISPLAY_Y 40
#define DMM_DISPLAY_WIDTH (LCD_WIDTH - 10)
#define DMM_DISPLAY_HEIGHT (LCD_HEIGHT/2 - 40)

/* Menu Mode */
#define MENU_MODE 0
#define OSCI_MODE 1
#define DMM_MODE 2

/* DMM Menu */
#define DMM_TEMP_MODE 1
#define DMM_CAP_MODE 2
#define DMM_RES_MODE 3
#define DMM_CONT_MODE 4
#define DMM_VOL_MODE 5
#define DMM_CUR_MODE 6

/* Time base options (seconds per division) */
#define ADC1_DR_ADDRESS ((uint32_t)0x4001204C)
const float time_bases[] = {1.0, 0.5, 0.25, 0.1, 0.05, 0.01, 0.005};
const char* time_base_labels[] = {"1s", "500ms", "250ms", "100ms", "50ms", "10ms", "5ms"};
uint8_t cur_time_base = 3; // Default: 100ms/div


/* Global variables for touch */
TM_STMPE811_TouchData TouchData;

/* Button IDs */
int8_t main_menu_button_id = -1;
int8_t dmm_button_id = -1;
int8_t osci_button_id = -1;

int8_t timebase_button_id = -1;
int8_t ch1_button_id = -1;
int8_t ch2_button_id = -1;
int8_t save_button_id = -1;
int8_t recall_button_id = -1;

int8_t dmm_temp_button_id = -1;
int8_t dmm_cap_button_id = -1;
int8_t dmm_res_button_id = -1;
int8_t dmm_cont_button_id = -1;
int8_t dmm_back_button_id = -1;
int8_t dmm_vol_button_id = -1;
int8_t dmm_cur_button_id = -1;


/* Add these for saving/recalling waveforms */
volatile uint8_t recall_CH1;
volatile uint8_t recall_CH2;
volatile uint32_t recalled_waveform[BUFFER_SIZE];
volatile uint8_t current_save_slot = 0;
volatile uint8_t recall_mode = 0;
volatile uint8_t recall_plot = 0;

/* Global variables */
static uint16_t old_y_ch1[MAX_POINTS];
static uint16_t old_y_ch2[MAX_POINTS];
static uint16_t recall_old_y_ch1[MAX_POINTS];
static uint16_t recall_old_y_ch2[MAX_POINTS];
volatile uint8_t cur_mode;
volatile uint32_t adc_buffer[BUFFER_SIZE];
volatile uint8_t refresh = 0;
volatile uint8_t buffer_ready = 0;
volatile uint8_t CH1_flag = 0; // 1 => plot Channel 1
volatile uint8_t CH2_flag = 0; // 1 => plot Channel 2
volatile uint16_t centre_idx = BUFFER_SIZE / 4; // Adjusted for dual channel
volatile uint16_t prev_centre_idx = BUFFER_SIZE / 4;

volatile uint8_t cap_measurement_active = 0;
volatile CapState_t capState = CAP_STATE_DISCHARGED;
volatile uint32_t cap_start_time = 0;
volatile float capacitance_value = 0.0f;
volatile uint8_t cap_measurement_done = 0;

volatile float Va;
volatile float Vb;
volatile float current_mA;

volatile uint8_t DMM_BUTTON_SEL = 0;

/* Waveform Measurements */
volatile float CH1_freq, CH1_avg, CH1_duty, CH1_vpp;
volatile float CH2_freq, CH2_avg, CH2_duty, CH2_vpp;

/* OSCI Basic Configuration Functions Prototype */
void float_to_str(float, char*, int);
void ShowSplashScreen(void);
void LCD_Config(void);

/* Buttons Functions Prototype */
void UI_Handler(void);
void DrawButtons(void);
void ProcessOSCITouch(uint16_t x, uint16_t y);
void ProcessMainMenuTouch(uint16_t x, uint16_t y);
void ProcessDmmMenuTouch(uint16_t x, uint16_t y);
void ProcessDMMSubMenuTouch(uint16_t x, uint16_t y);

/* Oscilloscope Functions Prototype */
void OSCI_Deinit(void);
void OSCI_Config(void);
void OSCIDMA_Config(void);
void OSCI_Timer(float time_per_div);
void Waveform_Timer(void);

/* Graph Plot Functions Prototype */
void PlotWaveform(void);
void PlotStatic(uint32_t*, uint16_t, uint8_t);
void CalculateMeasurement(uint32_t*);
void DrawGrid(void);
void DrawDottedLine(uint16_t, uint16_t, uint16_t, uint16_t, uint16_t);
void drawOSCchannel(uint8_t , uint16_t, uint8_t, uint16_t*, uint16_t* , uint16_t);
void DisplayMeasurement(void);

/* Save Waveform Functions Prototype */
void SaveWaveform_NAND(void);
void RecallWaveform_NAND(void);

/* DMM Result Display Function */
void DisplayCenteredTextInRectangle(uint16_t, uint16_t, uint16_t, uint16_t, char*, TM_FontDef_t*, uint16_t);

/* Resistance Measurement Functions Prototype */
void DMM_RES_Deint(void);
void DMM_RES_Config(void);
uint16_t ADC1_Read(uint8_t);
float resisMeasure(void);

/* Temperature Measurement Functions Prototype */
void DMM_TEMP_Deint(void);
void DMM_TEMP_Config(void);

/* Capacitance Measurement Functions Prototype */
void DMM_CAP_Deint(void);
void DMM_CAP_Config(void);
uint16_t CAP_ADC1_Read(void);
void Cap_Charge(void);
void Cap_Discharge(void);
void ProcessCapacitanceMeasurement(void);

/* Connectivity Measurement Functions Prototype */
void DMM_CON_Config(void);
void Buzzer_Control(uint8_t);

/* Voltage Current Measurement Functions Prototype */
void DMM_VOL_Deint(void);
void DMM_VOL_Config(void);
void VoltageMeasure(float*, float*,float*);



/*
**===========================================================================
**
**  Main Program
**
**===========================================================================
*/

int main(void) {

	char str[40];
	char temp[40];
    LCD_Config();
    FMC_NAND_Init();
    ShowSplashScreen();

    // Initialize touch controller
    if (TM_STMPE811_Init() != TM_STMPE811_State_Ok) {
        // Display error message
        TM_ILI9341_Puts(10, 10, "Touch Error!", &TM_Font_11x18, ILI9341_COLOR_RED, ILI9341_COLOR_BLACK);
        while(1);
    }

    // Small Delay
    for(int i = 0; i < 1000; i++);

    // Set touch orientation to match LCD
    TouchData.orientation = TM_STMPE811_Orientation_Landscape_2;

    cur_mode = MENU_MODE;
    TM_ILI9341_Fill(ILI9341_COLOR_BLACK);
    DrawButtons();

    // Main Loop
    while (1) {

    	/* Handle user input */
		UI_Handler();

		switch (cur_mode){

			case MENU_MODE:

				break;

			case DMM_MODE:

				if (cap_measurement_active) {

					ProcessCapacitanceMeasurement();

					// Update display when measurement is done
					if (cap_measurement_done) {
						cap_measurement_done = 0;

						// Clear only the display area
						 TM_ILI9341_DrawFilledRectangle(10, 50, LCD_WIDTH - 10, LCD_HEIGHT/2 - 10, ILI9341_COLOR_BLACK);

						float_to_str(capacitance_value, temp, 3);

						if (capacitance_value < 1.0f) {
							snprintf(str, sizeof(str), "%s uF", temp);
						}
						else if (capacitance_value < 1000.0f) {
							snprintf(str, sizeof(str), "%s uF", temp);
						}
						else {
							float mF_value = capacitance_value / 1000.0f;
							float_to_str(mF_value, temp, 3);
							snprintf(str, sizeof(str), "%s mF", temp);
						}
						DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y, DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT, str, &TM_Font_11x18, ILI9341_COLOR_WHITE);
					}
				}

				break;

			case OSCI_MODE:

				if (refresh) {
					refresh = 0;

					// Only process new data if not in recall mode
					if (!recall_mode) {

						/* Process ADC Data */
						DrawGrid();
						CalculateMeasurement((uint32_t*)adc_buffer);

						/* Update Display */
						PlotWaveform();
						DisplayMeasurement();

					}
					else {

						// Display recalled waveform
						DrawGrid();

						if (recall_plot) {
							recall_plot = 0;

							PlotWaveform();
							CalculateMeasurement((uint32_t*)recalled_waveform);
							DisplayMeasurement();
						}


					}
				}

				break;
		}
		// Small Delay
		for(int i = 0; i < 1000; i++);
    }
}

/*
**===========================================================================
**
**  Basic Configuration Function
**
**===========================================================================
*/



void float_to_str(float value, char* buffer, int decimal_places) {
    int integer_part = (int)value;
    float fractional_part = value - integer_part;

    for (int i = 0; i < decimal_places; i++) {
        fractional_part *= 10;
    }
    uint8_t fractional_int = (int)fractional_part;

    snprintf(buffer, 20, "%d.%d", integer_part, fractional_int);
}


void ShowSplashScreen(void) {
    uint16_t x, y;
    uint32_t pixel_idx;

    for (y=0; y < LCD_HEIGHT; y++){

    	for (x=0; x < LCD_WIDTH; x++){

    		pixel_idx = (y * 320) + x;
    		uint16_t pixel_color = Background[pixel_idx];
    		TM_ILI9341_DrawPixel(x, y, pixel_color);
    	}
    }

    for (volatile int i = 0; i < 3000000; i++);
}

// LCD Function Definition
void LCD_Config(void) {
    TM_ILI9341_Init();
    TM_ILI9341_Rotate(TM_ILI9341_Orientation_Landscape_2);
    TM_ILI9341_Fill(ILI9341_COLOR_BLACK);
}


/*
**===========================================================================
**
**  Buttons Function
**
**===========================================================================
*/

void UI_Handler(void) {
                     static uint32_t last_touch_time = 0;
    uint32_t current_time = SysTick->VAL;

    // Add debouncing - only check touch every 200ms
    if (current_time - last_touch_time < 200) {
        return;
    }

    // Read touch data
    if (TM_STMPE811_ReadTouch(&TouchData) == TM_STMPE811_State_Pressed) {
        last_touch_time = current_time;

        switch (cur_mode){

			case MENU_MODE:
				ProcessMainMenuTouch(TouchData.x, TouchData.y);
				break;

			case DMM_MODE:

				ProcessDmmMenuTouch(TouchData.x, TouchData.y);
				break;

			case OSCI_MODE:
				ProcessOSCITouch(TouchData.x, TouchData.y);
				break;
        }


    }
}

void ProcessMainMenuTouch(uint16_t x, uint16_t y){

	int8_t button_id = TM_ILI9341_Button_Touch(&TouchData);

	if (button_id >= 0) {

		if (button_id == dmm_button_id) {
			cur_mode = DMM_MODE;
			DMM_BUTTON_SEL = 0;
			// Initialize DMM
			TM_ILI9341_Fill(ILI9341_COLOR_BLACK);
			DrawButtons();
		}

		else if (button_id == osci_button_id) {

			cur_mode = OSCI_MODE;
			// Initialize oscilloscope
			OSCI_Config();
			OSCI_Timer(time_bases[cur_time_base]);
			OSCIDMA_Config();
			Waveform_Timer();


			CH1_freq = CH1_avg = CH1_duty = CH1_vpp = 0;
			CH2_freq = CH2_avg = CH2_duty = CH2_vpp = 0;

			// Draw oscilloscope UI
			TM_ILI9341_Fill(ILI9341_COLOR_BLACK);
			DrawGrid();
			DrawButtons();
		}
	}

}

void ProcessDmmMenuTouch(uint16_t x, uint16_t y){
    int8_t button_id = TM_ILI9341_Button_Touch(&TouchData);
    char str[40];
    char temp[40];

    if (button_id >= 0) {
        if (button_id == main_menu_button_id) {
            cur_mode = MENU_MODE;
            DMM_BUTTON_SEL = 0;
            TM_ILI9341_Fill(ILI9341_COLOR_BLACK);
            DrawButtons();
            return;
        }

        // Clear only the display area
        TM_ILI9341_DrawFilledRectangle(10, 50, LCD_WIDTH - 10, LCD_HEIGHT/2 - 10, ILI9341_COLOR_BLACK);

        if (button_id == dmm_temp_button_id) {
            DMM_CAP_Deint();
            DMM_VOL_Deint();
            DMM_TEMP_Deint();
            DMM_RES_Deint();

            cur_mode = DMM_MODE;
            DMM_BUTTON_SEL = DMM_TEMP_MODE;

            float Temp;
            int Temp_int,Temp_frac;
            char aTextBuffer[200];

            DHT22_Init();
            DMM_TEMP_Config();

            DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y,
                                                                  DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT,
                                                                  "Temperature Measuring....", &TM_Font_11x18, ILI9341_COLOR_WHITE);
            TM_ILI9341_DrawFilledRectangle(10, 50, LCD_WIDTH - 10, LCD_HEIGHT/2 - 10, ILI9341_COLOR_BLACK);
            DHT22_Read();

            Temp = DHT22getTemperature();
            Temp_int = (int)Temp;
            Temp_frac = (int)((Temp - Temp_int) * 10);

            // Update button highlights without redrawing everything
            DrawButtons();

            sprintf(aTextBuffer, "%d.%d C", Temp_int, Temp_frac);
            DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y,
                                          DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT,
                                          aTextBuffer, &TM_Font_11x18, ILI9341_COLOR_WHITE);
        }
        else if (button_id == dmm_cap_button_id) {
            DMM_CAP_Deint();
            DMM_VOL_Deint();
            DMM_TEMP_Deint();
            DMM_RES_Deint();

            cur_mode = DMM_MODE;
            DMM_BUTTON_SEL = DMM_CAP_MODE;

            DMM_CAP_Config();

            cap_measurement_active = 1;
            capState = CAP_STATE_DISCHARGED;
            cap_measurement_done = 0;
            capacitance_value = 0.0f;
            cap_start_time = TIM2->CNT;

            // Update button highlights
            DrawButtons();

            // Display initial message in the display area only
            DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y,
                                          DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT,
                                          "Capacitance Measuring...", &TM_Font_11x18, ILI9341_COLOR_WHITE);
        }
        else if (button_id == dmm_res_button_id) {
            DMM_CAP_Deint();
            DMM_VOL_Deint();
            DMM_TEMP_Deint();
            DMM_RES_Deint();

            cur_mode = DMM_MODE;
            DMM_BUTTON_SEL = DMM_RES_MODE;

            DMM_RES_Config();
            float read_value;
            read_value = resisMeasure();

            // Update button highlights
            DrawButtons();

            // Display resistance value in the display area only
            float_to_str(read_value, temp, 2);
            snprintf(str, sizeof(str), "%s Ohm", temp);
            DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y,
                                          DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT,
                                          str, &TM_Font_11x18, ILI9341_COLOR_WHITE);
        }
        else if (button_id == dmm_cont_button_id) {
            DMM_CAP_Deint();
            DMM_VOL_Deint();
            DMM_TEMP_Deint();
            DMM_RES_Deint();

            cur_mode = DMM_MODE;
            DMM_BUTTON_SEL = DMM_CONT_MODE;

            DMM_RES_Config();
            float read_value;
            read_value = resisMeasure();

            // Update button highlights
            DrawButtons();

            if ((read_value >= 0.0f) && (read_value <= 1.0f) ){
                Buzzer_Control(1);
                DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y,
                                              DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT,
                                              "Unconnected", &TM_Font_16x26, ILI9341_COLOR_RED);
            }
            else {
                Buzzer_Control(0);
                DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y,
                                              DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT,
                                              "Connected", &TM_Font_16x26, ILI9341_COLOR_BLUE);
            }
        }
        else if (button_id == dmm_vol_button_id) {
            DMM_CAP_Deint();
            DMM_VOL_Deint();
            DMM_TEMP_Deint();
            DMM_RES_Deint();

            cur_mode = DMM_MODE;
            DMM_BUTTON_SEL = DMM_VOL_MODE;

            float Va = 0.0f, Vb = 0.0f, Vrslt = 0.0f, current_mA = 0.0f;

            DMM_VOL_Config();
            VoltageMeasure(&Va, &Vb, &current_mA);

            // Update button highlights
            DrawButtons();

            Vrslt = Va - Vb;

            float_to_str(Vrslt, temp, 2);
            snprintf(str, sizeof(str), "%s V", temp);
            DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y,
                                          DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT,
                                          str, &TM_Font_11x18, ILI9341_COLOR_WHITE);
        }
        else if (button_id == dmm_cur_button_id) {
            DMM_CAP_Deint();
            DMM_VOL_Deint();
            DMM_TEMP_Deint();
            DMM_RES_Deint();

            cur_mode = DMM_MODE;
            DMM_BUTTON_SEL = DMM_CUR_MODE;

            float Va = 0.0f, Vb = 0.0f, current_mA = 0.0f;

            DMM_VOL_Config();
            VoltageMeasure(&Va, &Vb, &current_mA);

            // Update button highlights
            DrawButtons();

            float_to_str(current_mA, temp, 2);
            snprintf(str, sizeof(str), "%s mA", temp);
            DisplayCenteredTextInRectangle(DMM_DISPLAY_X, DMM_DISPLAY_Y,
                                          DMM_DISPLAY_WIDTH, DMM_DISPLAY_HEIGHT,
                                          str, &TM_Font_11x18, ILI9341_COLOR_WHITE);
        }
    }
}

void ProcessOSCITouch(uint16_t x, uint16_t y) {
    // Check if any button was pressed
    int8_t button_id = TM_ILI9341_Button_Touch(&TouchData);

    if (button_id >= 0) {

    	// Check if it's menu button
		if (button_id == main_menu_button_id) {
			OSCI_Deinit();
			CH1_flag = 0;
			CH2_flag = 0;
			recall_mode = 0;
			cur_mode = MENU_MODE;
			TM_ILI9341_Fill(ILI9341_COLOR_BLACK);
			DrawButtons();
			return;
		}

        // Check if it's the timebase button
        if (button_id == timebase_button_id) {
            // Cycle through time bases
            cur_time_base = (cur_time_base + 1) % 7;
            OSCI_Timer(time_bases[cur_time_base]);

            // Erase Graph
            TM_ILI9341_DrawFilledRectangle(GRID_X + 1, GRID_Y + 1, GRID_WIDTH - 2, GRID_HEIGHT - 2, ILI9341_COLOR_BLACK);
            DrawGrid();

            // Update display
            PlotWaveform();
            DisplayMeasurement();
            DrawButtons();
        }
        // Check if it's channel 1 button
        else if (button_id == ch1_button_id) {
            CH1_flag = !CH1_flag;

            // Erase Graph
            for (int x = 1; x < MAX_POINTS; x++) {
				if (!CH1_flag) {
					TM_ILI9341_DrawLine(GRID_X + x - 1, old_y_ch1[x - 1], GRID_X + x, old_y_ch1[x], ILI9341_COLOR_BLACK);
				}
				if (!CH2_flag) {
					TM_ILI9341_DrawLine(GRID_X + x - 1, old_y_ch2[x - 1], GRID_X + x, old_y_ch2[x], ILI9341_COLOR_BLACK);
				}
			}
			DrawGrid();

            // Update display
            PlotWaveform();
            DisplayMeasurement();
            DrawButtons();
        }
        // Check if it's channel 2 button
        else if (button_id == ch2_button_id) {
            CH2_flag = !CH2_flag;

            // Erase Graph
            for (int x = 1; x < MAX_POINTS; x++) {
				if (!CH1_flag) {
					TM_ILI9341_DrawLine(GRID_X + x - 1, old_y_ch1[x - 1], GRID_X + x, old_y_ch1[x], ILI9341_COLOR_BLACK);
				}
				if (!CH2_flag) {
					TM_ILI9341_DrawLine(GRID_X + x - 1, old_y_ch2[x - 1], GRID_X + x, old_y_ch2[x], ILI9341_COLOR_BLACK);
				}
			}
			DrawGrid();

            // Update display
            PlotWaveform();
            DisplayMeasurement();
            DrawButtons();
        }

        // Check if it's save button
        else if (button_id == save_button_id) {
            // Save current waveform to flash
        	SaveWaveform_NAND();

        	recall_CH1 = CH1_flag;
        	recall_CH2 = CH2_flag;
        }

        // Check if it's recall button
        else if (button_id == recall_button_id) {

        	recall_plot = 1;
        	recall_mode = !recall_mode;

        	if (recall_mode) {
				// First press - load and display saved waveform

				RecallWaveform_NAND();


			}
        	else {
				// Second press - clear recalled waveform and return to live mode
				// Erase Graph
        		for (int x = 1; x < MAX_POINTS; x++) {
					if (!CH1_flag) {
						TM_ILI9341_DrawLine(GRID_X + x - 1, recall_old_y_ch1[x - 1], GRID_X + x, recall_old_y_ch1[x], ILI9341_COLOR_BLACK);
					}
					if (!CH2_flag) {
						TM_ILI9341_DrawLine(GRID_X + x - 1, recall_old_y_ch2[x - 1], GRID_X + x, recall_old_y_ch2[x], ILI9341_COLOR_BLACK);
					}
				}

			}

			DrawButtons();
        }
    }
}

void DrawButtons(void) {

    // Delete all existing buttons and reset IDs
    TM_ILI9341_Button_DeleteAll();

    int button_width;

    main_menu_button_id = -1;
    dmm_button_id = -1;
    osci_button_id = -1;

    timebase_button_id = -1;
    ch1_button_id = -1;
    ch2_button_id = -1;
    save_button_id = -1;
    recall_button_id = -1;

    dmm_temp_button_id = -1;
    dmm_cap_button_id = -1;
    dmm_res_button_id = -1;
    dmm_cont_button_id = -1;
    dmm_vol_button_id = -1;
    dmm_cur_button_id = -1;

    switch (cur_mode){

		case MENU_MODE:

			TM_ILI9341_Puts(LCD_WIDTH/2 - 120, 20, "Instrument Mode", &TM_Font_16x26, ILI9341_COLOR_WHITE, ILI9341_COLOR_BLACK);

			// DMM Button
			TM_ILI9341_Button_t dmm_button;
			dmm_button.x = LCD_WIDTH/2 - 80;
			dmm_button.y = 80;
			dmm_button.width = 150;
			dmm_button.height = 50;
			dmm_button.background = ILI9341_COLOR_BLUE2;
			dmm_button.borderColor = ILI9341_COLOR_WHITE;
			dmm_button.label = "DMM";
			dmm_button.color = ILI9341_COLOR_WHITE;
			dmm_button.font = &TM_Font_11x18;
			dmm_button.flags = 0;
			dmm_button_id = TM_ILI9341_Button_Add(&dmm_button);

			// Oscilloscope Button
			TM_ILI9341_Button_t osci_button;
			osci_button.x = LCD_WIDTH/2 - 80;
			osci_button.y = 150;
			osci_button.width = 150;
			osci_button.height = 50;
			osci_button.background = ILI9341_COLOR_BLUE2;
			osci_button.borderColor = ILI9341_COLOR_WHITE;
			osci_button.label = "Oscilloscope";
			osci_button.color = ILI9341_COLOR_WHITE;
			osci_button.font = &TM_Font_11x18;
			osci_button.flags = 0;
			osci_button_id = TM_ILI9341_Button_Add(&osci_button);
			break;

		case DMM_MODE:

			// Title
			TM_ILI9341_Puts(LCD_WIDTH/2 - 70, 10, "DMM Functions", &TM_Font_11x18, ILI9341_COLOR_WHITE, ILI9341_COLOR_BLACK);
			TM_ILI9341_DrawRectangle(5, 40, LCD_WIDTH - 5, LCD_HEIGHT/2, ILI9341_COLOR_WHITE);

			// --- Temperature Button ---

			TM_ILI9341_Button_t temp_button;
			temp_button.x = 5;
			temp_button.y = LCD_HEIGHT - 55;
			temp_button.width = 100;
			temp_button.height = 50;
			temp_button.background = (DMM_BUTTON_SEL == DMM_TEMP_MODE) ? ILI9341_COLOR_BLUE2 : ILI9341_COLOR_GRAY;
			temp_button.borderColor = ILI9341_COLOR_WHITE;
			temp_button.label = "Temperature";
			temp_button.color = ILI9341_COLOR_WHITE;
			temp_button.font = &TM_Font_7x10;
			temp_button.flags = 0;
			dmm_temp_button_id = TM_ILI9341_Button_Add(&temp_button);


			// --- Capacitance Button ---

			TM_ILI9341_Button_t cap_button;
			cap_button.x = 110;
			cap_button.y = LCD_HEIGHT - 55;
			cap_button.width = 100;
			cap_button.height = 50;
			cap_button.background = (DMM_BUTTON_SEL == DMM_CAP_MODE) ? ILI9341_COLOR_BLUE2 : ILI9341_COLOR_GRAY;
			cap_button.borderColor = ILI9341_COLOR_WHITE;
			cap_button.label = "Capacitance";
			cap_button.color = ILI9341_COLOR_WHITE;
			cap_button.font = &TM_Font_7x10;
			cap_button.flags = 0;
			dmm_cap_button_id = TM_ILI9341_Button_Add(&cap_button);



			// --- Connectivity Button ---

			TM_ILI9341_Button_t cont_button;
			cont_button.x = 215;
			cont_button.y = LCD_HEIGHT - 55;
			cont_button.width = 100;
			cont_button.height = 50;
			cont_button.background = (DMM_BUTTON_SEL == DMM_CONT_MODE) ? ILI9341_COLOR_BLUE2 : ILI9341_COLOR_GRAY;
			cont_button.borderColor = ILI9341_COLOR_WHITE;
			cont_button.label = "Connectivity";
			cont_button.color = ILI9341_COLOR_WHITE;
			cont_button.font = &TM_Font_7x10;
			cont_button.flags = 0;
			dmm_cont_button_id = TM_ILI9341_Button_Add(&cont_button);


			// --- Resistance Button ---

			TM_ILI9341_Button_t res_button;
			res_button.x = 5;
			res_button.y = LCD_HEIGHT - 110;
			res_button.width = 100;
			res_button.height = 50;
			res_button.background = (DMM_BUTTON_SEL == DMM_RES_MODE) ? ILI9341_COLOR_BLUE2 : ILI9341_COLOR_GRAY;
			res_button.borderColor = ILI9341_COLOR_WHITE;
			res_button.label = "Resistance";
			res_button.color = ILI9341_COLOR_WHITE;
			res_button.font = &TM_Font_7x10;
			res_button.flags = 0;
			dmm_res_button_id = TM_ILI9341_Button_Add(&res_button);



			// --- Voltage Button ---

			TM_ILI9341_Button_t vol_button;
			vol_button.x = 110;
			vol_button.y = LCD_HEIGHT - 110;
			vol_button.width = 100;
			vol_button.height = 50;
			vol_button.background = (DMM_BUTTON_SEL == DMM_VOL_MODE) ? ILI9341_COLOR_BLUE2 : ILI9341_COLOR_GRAY;
			vol_button.borderColor = ILI9341_COLOR_WHITE;
			vol_button.label = "Voltage";
			vol_button.color = ILI9341_COLOR_WHITE;
			vol_button.font = &TM_Font_7x10;
			vol_button.flags = 0;
			dmm_vol_button_id = TM_ILI9341_Button_Add(&vol_button);


			// --- Current Button ---

			TM_ILI9341_Button_t cur_button;
			cur_button.x = 215;
			cur_button.y = LCD_HEIGHT - 110;
			cur_button.width = 100;
			cur_button.height = 50;
			cur_button.background = (DMM_BUTTON_SEL == DMM_CUR_MODE) ? ILI9341_COLOR_BLUE2 : ILI9341_COLOR_GRAY;
			cur_button.borderColor = ILI9341_COLOR_WHITE;
			cur_button.label = "Current";
			cur_button.color = ILI9341_COLOR_WHITE;
			cur_button.font = &TM_Font_7x10;
			cur_button.flags = 0;
			dmm_cur_button_id = TM_ILI9341_Button_Add(&cur_button);


			// --- Main Menu Button ---
			TM_ILI9341_Button_t main_menu_button;
			main_menu_button.x = LCD_WIDTH - 50;
			main_menu_button.y = 5;
			main_menu_button.width = 40;
			main_menu_button.height = 25;
			main_menu_button.background = ILI9341_COLOR_BLACK;
			main_menu_button.borderColor = ILI9341_COLOR_WHITE;
			main_menu_button.label = "Main";
			main_menu_button.color = ILI9341_COLOR_WHITE;
			main_menu_button.font = &TM_Font_7x10;
			main_menu_button.flags = 0;
			main_menu_button_id = TM_ILI9341_Button_Add(&main_menu_button);

			break;

		case OSCI_MODE:

			// Bottom buttons - Timebase, CH1, CH2
			button_width = GRID_WIDTH / 3;

			// Timebase button (replaces the menu button in the bottom row)
			TM_ILI9341_Button_t timebase_button;
			timebase_button.x = 0 + 2;
			timebase_button.y = GRID_Y + GRID_HEIGHT + 5;
			timebase_button.width = button_width - 2;
			timebase_button.height = BOTTOM_BUTTON_HEIGHT - 10;
			timebase_button.background = ILI9341_COLOR_BLUE;
			timebase_button.borderColor = ILI9341_COLOR_WHITE;
			timebase_button.flags = 0;
			timebase_button.label = time_base_labels[cur_time_base];
			timebase_button.color = ILI9341_COLOR_WHITE;
			timebase_button.font = &TM_Font_7x10;
			timebase_button.image = NULL;
			timebase_button_id = TM_ILI9341_Button_Add(&timebase_button);

			// Channel 1 button
			TM_ILI9341_Button_t ch1_button;
			ch1_button.x = button_width + 2;
			ch1_button.y = GRID_Y + GRID_HEIGHT + 5;
			ch1_button.width = button_width - 2;
			ch1_button.height = BOTTOM_BUTTON_HEIGHT - 10;
			ch1_button.background = CH1_flag ? ILI9341_COLOR_YELLOW : ILI9341_COLOR_GRAY;
			ch1_button.borderColor = ILI9341_COLOR_WHITE;
			ch1_button.flags = 0;
			ch1_button.label = "CH1";
			ch1_button.color = CH1_flag ? ILI9341_COLOR_BLACK : ILI9341_COLOR_WHITE;
			ch1_button.font = &TM_Font_7x10;
			ch1_button.image = NULL;
			ch1_button_id = TM_ILI9341_Button_Add(&ch1_button);

			// Channel 2 button
			TM_ILI9341_Button_t ch2_button;
			ch2_button.x = button_width * 2 + 2;
			ch2_button.y = GRID_Y + GRID_HEIGHT + 5;
			ch2_button.width = button_width - 2;
			ch2_button.height = BOTTOM_BUTTON_HEIGHT - 10;
			ch2_button.background = CH2_flag ? ILI9341_COLOR_CYAN : ILI9341_COLOR_GRAY;
			ch2_button.borderColor = ILI9341_COLOR_WHITE;
			ch2_button.flags = 0;
			ch2_button.label = "CH2";
			ch2_button.color = CH2_flag ? ILI9341_COLOR_BLACK : ILI9341_COLOR_WHITE;
			ch2_button.font = &TM_Font_7x10;
			ch2_button.image = NULL;
			ch2_button_id = TM_ILI9341_Button_Add(&ch2_button);

			// Right side buttons - Main, Save, Recall
			int button_height = (LCD_HEIGHT - 30) / 3;

			// Main button (moved to right side)
			TM_ILI9341_Button_t main_button;
			main_button.x = GRID_WIDTH + 5;
			main_button.y = GRID_Y;
			main_button.width = RIGHT_BUTTON_WIDTH - 10;
			main_button.height = button_height - 5;
			main_button.background = ILI9341_COLOR_BLACK;
			main_button.borderColor = ILI9341_COLOR_WHITE;
			main_button.flags = 0;
			main_button.label = "Main";
			main_button.color = ILI9341_COLOR_WHITE;
			main_button.font = &TM_Font_7x10;
			main_button.image = NULL;
			main_menu_button_id = TM_ILI9341_Button_Add(&main_button);

			// Save button
			TM_ILI9341_Button_t save_button;
			save_button.x = GRID_WIDTH + 5;
			save_button.y = GRID_Y + button_height;
			save_button.width = RIGHT_BUTTON_WIDTH - 10;
			save_button.height = button_height - 5;
			save_button.background = ILI9341_COLOR_ORANGE;
			save_button.borderColor = ILI9341_COLOR_WHITE;
			save_button.flags = 0;
			save_button.label = "Save";
			save_button.color = ILI9341_COLOR_WHITE;
			save_button.font = &TM_Font_7x10;
			save_button.image = NULL;
			save_button_id = TM_ILI9341_Button_Add(&save_button);

			// Recall button
			TM_ILI9341_Button_t recall_button;
			recall_button.x = GRID_WIDTH + 5;
			recall_button.y = GRID_Y + button_height * 2;
			recall_button.width = RIGHT_BUTTON_WIDTH - 10;
			recall_button.height = button_height - 2;
			recall_button.background = recall_mode ? ILI9341_COLOR_BROWN : ILI9341_COLOR_GRAY;
			recall_button.borderColor = ILI9341_COLOR_WHITE;
			recall_button.flags = 0;
			recall_button.label = "Call";
			recall_button.color = ILI9341_COLOR_WHITE;
			recall_button.font = &TM_Font_7x10;
			recall_button.image = NULL;
			recall_button_id = TM_ILI9341_Button_Add(&recall_button);

			break;

    }

    // Draw all buttons
    TM_ILI9341_Button_DrawAll();
}

/*
**===========================================================================
**
**  Oscilloscope Basic Functions
**
**===========================================================================
*/

void OSCI_Deinit(void) {
    // Disable DMA
    DMA_Cmd(DMA2_Stream0, DISABLE);
    DMA_DeInit(DMA2_Stream0);

    // Disable ADC
    ADC_Cmd(ADC1, DISABLE);
    ADC_DeInit();

    // Disable TIM2 (ADC trigger)
    TIM_Cmd(TIM2, DISABLE);
    TIM_DeInit(TIM2);

    // Disable TIM3 (display refresh)
    TIM_Cmd(TIM3, DISABLE);
    TIM_DeInit(TIM3);

    // Disable interrupts
    NVIC_InitTypeDef NVIC_InitStructure;

    // Disable DMA interrupt
    NVIC_InitStructure.NVIC_IRQChannel = DMA2_Stream0_IRQn;
    NVIC_InitStructure.NVIC_IRQChannelCmd = DISABLE;
    NVIC_Init(&NVIC_InitStructure);

    // Disable TIM3 interrupt
    NVIC_InitStructure.NVIC_IRQChannel = TIM3_IRQn;
    NVIC_InitStructure.NVIC_IRQChannelCmd = DISABLE;
    NVIC_Init(&NVIC_InitStructure);
}

// Waveform Refresh Rate
void Waveform_Timer(void){
    // Enable Screen Timer
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM3, ENABLE);

    // Screen Timer Configuration
    TIM_TimeBaseInitTypeDef TIM3_InitStructure;
    TIM3_InitStructure.TIM_Prescaler = 9999;
    TIM3_InitStructure.TIM_CounterMode = TIM_CounterMode_Up;
    TIM3_InitStructure.TIM_Period = 299;
    TIM3_InitStructure.TIM_ClockDivision = TIM_CKD_DIV1;
    TIM3_InitStructure.TIM_RepetitionCounter = 0;

    TIM_TimeBaseInit(TIM3, &TIM3_InitStructure);
    TIM_ITConfig(TIM3, TIM_IT_Update, ENABLE);

    // Screen Timer Interrupts
    NVIC_InitTypeDef NVIC_InitStructure;
    NVIC_InitStructure.NVIC_IRQChannel = TIM3_IRQn;
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
    NVIC_Init(&NVIC_InitStructure);

    TIM_Cmd(TIM3, ENABLE);
}

// Oscilloscope Function Definition
void OSCI_Config(void){
    // Enable GPIOC clock
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOC, ENABLE);

    // Enable ADC1 clock
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);

    // Configure ADC CH10 CH11 (PC0 and PC1)
    GPIO_InitTypeDef GPIO_InitStructure;
    GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0 | GPIO_Pin_1;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AN;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
    GPIO_Init(GPIOC, &GPIO_InitStructure);

    // ADC Common Initialization
    ADC_CommonInitTypeDef ADC_CommonInitStructure;
    ADC_CommonInitStructure.ADC_Mode = ADC_Mode_Independent;
    ADC_CommonInitStructure.ADC_Prescaler = ADC_Prescaler_Div4;
    ADC_CommonInitStructure.ADC_DMAAccessMode = ADC_DMAAccessMode_Disabled;
    ADC_CommonInitStructure.ADC_TwoSamplingDelay = ADC_TwoSamplingDelay_5Cycles;
    ADC_CommonInit(&ADC_CommonInitStructure);

    // ADC1 Initialization
    ADC_InitTypeDef ADC_InitStructure;
    ADC_InitStructure.ADC_Resolution = ADC_Resolution_12b;
    ADC_InitStructure.ADC_ScanConvMode = ENABLE;
    ADC_InitStructure.ADC_ContinuousConvMode = DISABLE;
    ADC_InitStructure.ADC_ExternalTrigConvEdge = ADC_ExternalTrigConvEdge_Rising;
    ADC_InitStructure.ADC_ExternalTrigConv = ADC_ExternalTrigConv_T2_TRGO;
    ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;
    ADC_InitStructure.ADC_NbrOfConversion = 2;
    ADC_Init(ADC1, &ADC_InitStructure);

    // PC0 = ADC123_IN10
    ADC_RegularChannelConfig(ADC1, ADC_Channel_10, 1, ADC_SampleTime_28Cycles);

    // PC1 = ADC123_IN11
    ADC_RegularChannelConfig(ADC1, ADC_Channel_11, 2, ADC_SampleTime_28Cycles);

    ADC_DMARequestAfterLastTransferCmd(ADC1, ENABLE);

    // Enable ADC DMA
    ADC_DMACmd(ADC1, ENABLE);

    // Enable ADC
    ADC_Cmd(ADC1, ENABLE);
}

// Oscilloscope Timer Function Definition
void OSCI_Timer(float time_per_div){
    // Calculate sampling rate
    float sample_rate = (SAMPLES_PER_DIV * HORIZ_DIV) / time_per_div;
    uint32_t timer_freq = (uint32_t)sample_rate;

    // Enable TIM2 clock
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);

    // Time Base Configuration
    TIM_TimeBaseInitTypeDef TIM_BaseStructure;
    TIM_TimeBaseStructInit(&TIM_BaseStructure);
    TIM_BaseStructure.TIM_Period = (SystemCoreClock / timer_freq) - 1;
    TIM_BaseStructure.TIM_Prescaler = 0;
    TIM_BaseStructure.TIM_ClockDivision = 0;
    TIM_BaseStructure.TIM_CounterMode = TIM_CounterMode_Up;
    TIM_TimeBaseInit(TIM2, &TIM_BaseStructure);

    // Configure TIM2 to trigger ADC
    TIM_SelectOutputTrigger(TIM2, TIM_TRGOSource_Update);

    // Enable TIM2
    TIM_Cmd(TIM2, ENABLE);
}

// DMA Function Definition
void OSCIDMA_Config(void) {

    // Enable DMA2 clock
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_DMA2, ENABLE);

    // DMA2 Stream0 Configuration
    DMA_InitTypeDef DMA_InitStructure;
    DMA_InitStructure.DMA_Channel = DMA_Channel_0;
    DMA_InitStructure.DMA_PeripheralBaseAddr = (uint32_t)ADC1_DR_ADDRESS;
    DMA_InitStructure.DMA_Memory0BaseAddr = (uint32_t)adc_buffer;
    DMA_InitStructure.DMA_DIR = DMA_DIR_PeripheralToMemory;
    DMA_InitStructure.DMA_BufferSize = BUFFER_SIZE;
    DMA_InitStructure.DMA_PeripheralInc = DMA_PeripheralInc_Disable;
    DMA_InitStructure.DMA_MemoryInc = DMA_MemoryInc_Enable;
    DMA_InitStructure.DMA_PeripheralDataSize = DMA_PeripheralDataSize_HalfWord;
    DMA_InitStructure.DMA_MemoryDataSize = DMA_MemoryDataSize_HalfWord;
    DMA_InitStructure.DMA_Mode = DMA_Mode_Circular;
    DMA_InitStructure.DMA_Priority = DMA_Priority_High;
    DMA_InitStructure.DMA_FIFOMode = DMA_FIFOMode_Disable;
    DMA_InitStructure.DMA_FIFOThreshold = DMA_FIFOThreshold_HalfFull;
    DMA_InitStructure.DMA_MemoryBurst = DMA_MemoryBurst_Single;
    DMA_InitStructure.DMA_PeripheralBurst = DMA_PeripheralBurst_Single;
    DMA_Init(DMA2_Stream0, &DMA_InitStructure);

    // Enable DMA interrupt
    DMA_ITConfig(DMA2_Stream0, DMA_IT_TC, ENABLE);

    // Enable DMA
    DMA_Cmd(DMA2_Stream0, ENABLE);

    // DMA interrupt configuration
    NVIC_InitTypeDef NVIC_InitStructure;
    NVIC_InitStructure.NVIC_IRQChannel = DMA2_Stream0_IRQn;
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
    NVIC_Init(&NVIC_InitStructure);

}


/*
**===========================================================================
**
**  Graph Plot Functions
**
**===========================================================================
*/

void PlotWaveform(void) {

        // --- Clear old waveforms ---
        for (int x = 1; x < MAX_POINTS; x++) {
            if (CH1_flag) {
                TM_ILI9341_DrawLine(GRID_X + x - 1, old_y_ch1[x - 1], GRID_X + x, old_y_ch1[x], ILI9341_COLOR_BLACK);
            }
            if (CH2_flag) {
                TM_ILI9341_DrawLine(GRID_X + x - 1, old_y_ch2[x - 1], GRID_X + x, old_y_ch2[x], ILI9341_COLOR_BLACK);
            }
        }

        // --- Redraw grid/axis ---
        DrawGrid();

        // --- Safe DMA read pointer ---
        uint16_t dma_write_ptr = BUFFER_SIZE - DMA_GetCurrDataCounter(DMA2_Stream0);
        uint16_t current_pair_start_idx = dma_write_ptr & 0xFFFE; // even align
        uint16_t read_start_idx = (current_pair_start_idx + 2) % BUFFER_SIZE;

        // --- Reset old_y arrays ---
        memset(old_y_ch1, 0, sizeof(old_y_ch1));
        memset(old_y_ch2, 0, sizeof(old_y_ch2));
        memset(recall_old_y_ch1, 0, sizeof(recall_old_y_ch1));
        memset(recall_old_y_ch2, 0, sizeof(recall_old_y_ch2));


        if (!recall_mode) {

        	// --- Draw new CH1 waveform ---
        	if (CH1_flag) {
				drawOSCchannel(1, read_start_idx, 1, (uint16_t*)adc_buffer, old_y_ch1, ILI9341_COLOR_YELLOW);
			}

			// --- Draw new CH2 waveform ---
			if (CH2_flag) {
				drawOSCchannel(2, read_start_idx, 1, (uint16_t*)adc_buffer, old_y_ch2, ILI9341_COLOR_CYAN);
			}
        }
        else {

        	// --- Draw new CH1 waveform ---
        	if (recall_CH1) {
        		drawOSCchannel(1, read_start_idx, 1, (uint16_t*)recalled_waveform, recall_old_y_ch1, ILI9341_COLOR_YELLOW);
			}

			// --- Draw new CH2 waveform ---
			if (recall_CH1) {
				drawOSCchannel(2, read_start_idx, 1, (uint16_t*)recalled_waveform, recall_old_y_ch2, ILI9341_COLOR_CYAN);
			}



        }

}


void drawOSCchannel(uint8_t channel, uint16_t start_idx, uint8_t decimation, uint16_t* buffer, uint16_t* old_y, uint16_t color) {

    uint16_t prev_y, current_y;
    uint8_t offset = (channel == 1) ? 0 : 1;

    // First sample
    uint16_t adc_first = buffer[start_idx + offset];
    float v_first = (float)adc_first * (3.3f / 4095.0f);
    prev_y = GRID_Y + GRID_HEIGHT - (uint16_t)((v_first / 3.3f) * GRID_HEIGHT);
    if (prev_y < GRID_Y) prev_y = GRID_Y;
    if (prev_y > GRID_Y + GRID_HEIGHT) prev_y = GRID_Y + GRID_HEIGHT;
    old_y[0] = prev_y;

    // Draw across screen
    for (int x = 1; x < MAX_POINTS; x++) {
        uint16_t idx = (start_idx + x * decimation * 2 + offset) % BUFFER_SIZE;
        uint16_t adc_val = buffer[idx];
        float v = (float)adc_val * (3.3f / 4095.0f);
        current_y = GRID_Y + GRID_HEIGHT - (uint16_t)((v / 3.3f) * GRID_HEIGHT);

        if (current_y < GRID_Y) current_y = GRID_Y;
        if (current_y > GRID_Y + GRID_HEIGHT) current_y = GRID_Y + GRID_HEIGHT;

        TM_ILI9341_DrawLine(GRID_X + x - 1, prev_y, GRID_X + x, current_y, color);

        old_y[x] = current_y;
        prev_y = current_y;
    }
}



void CalculateMeasurement(uint32_t* interleaved_samples) {

    uint16_t min_ch1 = 4095, max_ch1 = 0;
    uint16_t min_ch2 = 4095, max_ch2 = 0;
    uint32_t sum_ch1 = 0, sum_ch2 = 0;

    // Process all samples for both channels separately
    for (int i = 0; i < BUFFER_SIZE; i++) {
        // Extract both channels
    	uint16_t sample_ch1 = interleaved_samples[i] & 0xFFFF;         // Lower 16 bits (CH1)
    	uint16_t sample_ch2 = (interleaved_samples[i] >> 16) & 0xFFFF; // Upper 16 bits (CH2)

        // CH1 calculations
        if (sample_ch1 < min_ch1) min_ch1 = sample_ch1;
        if (sample_ch1 > max_ch1) max_ch1 = sample_ch1;
        sum_ch1 += sample_ch1;

        // CH2 calculations
        if (sample_ch2 < min_ch2) min_ch2 = sample_ch2;
        if (sample_ch2 > max_ch2) max_ch2 = sample_ch2;
        sum_ch2 += sample_ch2;
    }

    // Calculate measurements for CH1
    CH1_vpp = ((max_ch1 - min_ch1) * 3.3f) / 4095.0f;
    CH1_avg = (sum_ch1 / (float)BUFFER_SIZE) * 3.3f / 4095.0f;

    // Calculate measurements for CH2
    CH2_vpp = ((max_ch2 - min_ch2) * 3.3f) / 4095.0f;
    CH2_avg = (sum_ch2 / (float)BUFFER_SIZE) * 3.3f / 4095.0f;

    // Calculate frequency for both channels

	float period =  SAMPLES_PER_DIV / time_bases[cur_time_base];
	CH1_freq = period;

	period =  SAMPLES_PER_DIV / time_bases[cur_time_base];
	CH2_freq = period;


    // Duty cycle measurement for both channels
    if (max_ch1 - min_ch1 > 100) {
        int high_count_ch1 = 0;
        uint16_t threshold_ch1 = (max_ch1 + min_ch1) / 2;

        for (int i = 0; i < BUFFER_SIZE; i++) {
            uint16_t sample_ch1 = interleaved_samples[i];
            if (sample_ch1 > threshold_ch1) {
                high_count_ch1++;
            }
        }
        CH1_duty = (high_count_ch1 / (float)BUFFER_SIZE) * 100.0f;
    }
    else {
        CH1_duty = 0;
    }

    if (max_ch2 - min_ch2 > 100) {
        int high_count_ch2 = 0;
        uint16_t threshold_ch2 = (max_ch2 + min_ch2) / 2;

        for (int i = 0; i < BUFFER_SIZE; i++) {
            uint16_t sample_ch2 = interleaved_samples[i];
            if (sample_ch2 > threshold_ch2) {
                high_count_ch2++;
            }
        }
        CH2_duty = (high_count_ch2 / (float)BUFFER_SIZE) * 100.0f;
    }
    else {
        CH2_duty = 0;
    }


    if (!CH1_flag){
    	CH1_vpp = 0;
		CH1_avg = 0;
		CH1_freq = 0;
		CH1_duty = 0;
    }

    if (!CH2_flag){
    	CH2_vpp = 0;
		CH2_avg = 0;
		CH2_freq = 0;
		CH2_duty = 0;
    }

}

void DisplayMeasurement(void) {
    char str[32];
    char temp[32];
    uint16_t y_offset = 3;

    float ch1_freq = 0, ch1_avg = 0, ch1_duty = 0, ch1_vpp = 0;
    float ch2_freq = 0, ch2_avg = 0, ch2_duty = 0, ch2_vpp = 0;

    ch1_freq = CH1_freq;
	ch1_avg = CH1_avg;
	ch1_duty = CH1_duty;
	ch1_vpp = CH1_vpp;

	ch2_freq = CH2_freq;
	ch2_avg = CH2_avg;
	ch2_duty = CH2_duty;
	ch2_vpp = CH2_vpp;

    // CH1 Additional range checks
    if (ch1_freq > 1000000.0f || ch1_freq < 0) ch1_freq = 0;
    if (ch1_avg > 10.0f || ch1_avg < -10.0f) ch1_avg = 0;
    if (ch1_duty > 100.0f || ch1_duty < 0) ch1_duty = 0;
    if (ch1_vpp > 10.0f || ch1_vpp < 0) ch1_vpp = 0;

    // Display the CH1 measurements

    float_to_str(ch1_freq, temp, 2);
    snprintf(str, sizeof(str), "Freq:%sHz", temp);
    TM_ILI9341_Puts(1, y_offset, str, &TM_Font_7x10, ILI9341_COLOR_YELLOW, ILI9341_COLOR_BLACK);

    float_to_str(ch1_avg, temp, 2);
    snprintf(str, sizeof(str), "Avg:%sV", temp);
    TM_ILI9341_Puts(100, y_offset, str, &TM_Font_7x10, ILI9341_COLOR_YELLOW, ILI9341_COLOR_BLACK);

    float_to_str(ch1_duty, temp, 2);
    snprintf(str, sizeof(str), "Duty:%s%%", temp);
    TM_ILI9341_Puts(170, y_offset, str, &TM_Font_7x10, ILI9341_COLOR_YELLOW, ILI9341_COLOR_BLACK);

    float_to_str(ch1_vpp, temp, 2);
    snprintf(str, sizeof(str), "Vpp:%sV", temp);
    TM_ILI9341_Puts(255, y_offset, str, &TM_Font_7x10, ILI9341_COLOR_YELLOW, ILI9341_COLOR_BLACK);

    // CH1 Additional range checks
	if (ch2_freq > 1000000.0f || ch2_freq < 0) ch2_freq = 0;
	if (ch2_avg > 10.0f || ch2_avg < -10.0f) ch2_avg = 0;
	if (ch2_duty > 100.0f || ch2_duty < 0) ch2_duty = 0;
	if (ch2_vpp > 10.0f || ch2_vpp < 0) ch2_vpp = 0;

	// Display the CH2 measurements

	float_to_str(ch2_freq, temp, 2);
	snprintf(str, sizeof(str), "Freq:%sHz", temp);
	TM_ILI9341_Puts(1, y_offset + 15, str, &TM_Font_7x10, ILI9341_COLOR_CYAN, ILI9341_COLOR_BLACK);

	float_to_str(ch2_avg, temp, 2);
	snprintf(str, sizeof(str), "Avg:%sV", temp);
	TM_ILI9341_Puts(100, y_offset + 15, str, &TM_Font_7x10, ILI9341_COLOR_CYAN, ILI9341_COLOR_BLACK);

	float_to_str(ch2_duty, temp, 2);
	snprintf(str, sizeof(str), "Duty:%s%%", temp);
	TM_ILI9341_Puts(170, y_offset + 15, str, &TM_Font_7x10, ILI9341_COLOR_CYAN, ILI9341_COLOR_BLACK);

	float_to_str(ch2_vpp, temp, 2);
	snprintf(str, sizeof(str), "Vpp:%sV", temp);
	TM_ILI9341_Puts(245, y_offset + 15, str, &TM_Font_7x10, ILI9341_COLOR_CYAN, ILI9341_COLOR_BLACK);

}


void DrawDottedLine(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t color) {
    int dx = abs(x1 - x0);
    int dy = abs(y1 - y0);
    int sx = (x0 < x1) ? 1 : -1;
    int sy = (y0 < y1) ? 1 : -1;
    int err = dx - dy;
    int e2;
    int dotCounter = 0;

    while(1) {
        if (dotCounter % 8 < 2) { // Draw 2 pixels, skip 2 pixels
            TM_ILI9341_DrawPixel(x0, y0, color);
        }
        dotCounter++;

        if (x0 == x1 && y0 == y1) break;

        e2 = 2 * err;
        if (e2 > -dy) {
            err -= dy;
            x0 += sx;
        }
        if (e2 < dx) {
            err += dx;
            y0 += sy;
        }
    }
}

void DrawGrid(void) {
    // Draw horizontal grid lines
    for (int i = 0; i <= VERT_DIV; i++) {
        int y = GRID_Y + i * PIXELS_PER_DIV_V;

        if ((i == 0) || (i == VERT_DIV)){
            TM_ILI9341_DrawLine(GRID_X, y, GRID_X + GRID_WIDTH, y, ILI9341_COLOR_WHITE);
        }
        else {
            DrawDottedLine(GRID_X, y, GRID_X + GRID_WIDTH, y, ILI9341_COLOR_GRAY);
        }
    }

    // Draw vertical grid lines
    for (int i = 0; i <= HORIZ_DIV; i++) {
        int x = GRID_X + i * PIXELS_PER_DIV_H;

        if ((i == 0) || (i == HORIZ_DIV)){
            TM_ILI9341_DrawLine(x, GRID_Y, x, GRID_Y + GRID_HEIGHT, ILI9341_COLOR_WHITE);
        }
        else {
            DrawDottedLine(x, GRID_Y, x, GRID_Y + GRID_HEIGHT, ILI9341_COLOR_GRAY);
        }
    }
}


/*
**===========================================================================
**
**  Save Waveform Functions
**
**===========================================================================
*/

/* Save Waveform Functions for NAND Flash - CORRECTED */
void SaveWaveform_NAND(void) {
	// 1. Define the physical address to write to.
	    //    We'll use Zone 0, Block 10, Page 0.
	    NAND_ADDRESS save_address;
	    save_address.Zone = 0;
	    save_address.Block = 10;
	    save_address.Page = 0;
	    uint8_t *buffer_ptr= (uint8_t *)adc_buffer;

	    int remain_byte = BUFFER_SIZE * 4;
	    static uint8_t page_buffer[NAND_PAGE_SIZE];
		FMC_NAND_EraseBlock(save_address);

	    while(remain_byte > 0){

	    	uint32_t size_cpy = (remain_byte > NAND_PAGE_SIZE) ? NAND_PAGE_SIZE:  remain_byte;

			memcpy(page_buffer, buffer_ptr, size_cpy);

			FMC_NAND_WriteSmallPage(page_buffer, save_address, 1);
			//inc page
			FMC_NAND_AddressIncrement(&save_address);

			remain_byte -= NAND_PAGE_SIZE;
			buffer_ptr += NAND_PAGE_SIZE;
	    }
}

void RecallWaveform_NAND(void) {
	// 1. Define the same address we saved to.
	    NAND_ADDRESS recall_address;
	    recall_address.Zone = 0;
	    recall_address.Block = 10;
	    recall_address.Page = 0;
	    uint8_t *buffer_ptr= (uint8_t *)recalled_waveform;

	    // 2. Read one full page (2048 bytes) from the NAND flash.
	    //    Our 960 bytes of data will be at the beginning of the received data.

	    // Now, 'read_nand_buffer' contains the recalled waveform.
	    // You can proceed to display it on the LCD.

	    int remain_byte = BUFFER_SIZE*4;
		static uint8_t page_buffer[NAND_PAGE_SIZE];
		while(remain_byte>0){
			uint32_t size_read = remain_byte > NAND_PAGE_SIZE ? NAND_PAGE_SIZE:  remain_byte;

			FMC_NAND_ReadSmallPage(page_buffer, recall_address, 1); // Reading 1 page
			//inc page
			FMC_NAND_AddressIncrement(&recall_address);
			memcpy(buffer_ptr, page_buffer, size_read * sizeof(uint32_t));
			remain_byte -=NAND_PAGE_SIZE;
			buffer_ptr+=NAND_PAGE_SIZE;
		}
}


/*
**===========================================================================
**
**  Digital Multimeter Function Definition
**
**===========================================================================
*/

void DisplayCenteredTextInRectangle(uint16_t rect_x, uint16_t rect_y, uint16_t rect_width, uint16_t rect_height, char* text, TM_FontDef_t* font, uint16_t color) {
    // Calculate text dimensions (approximate)
    uint16_t text_width = strlen(text) * font->FontWidth;
    uint16_t text_height = font->FontHeight;

    // Calculate center position
    uint16_t center_x = rect_x + (rect_width - text_width) / 2;
    uint16_t center_y = rect_y + (rect_height - text_height) / 2;

    // Display text
    TM_ILI9341_Puts(center_x, center_y, text, font, color, ILI9341_COLOR_BLACK);
}

/* Resistance Measurement Functions Definition */
void DMM_RES_Config(void){

	ADC_InitTypeDef       ADC_InitStructure;
	ADC_CommonInitTypeDef ADC_CommonInitStructure;
	GPIO_InitTypeDef      GPIO_InitStructure;

	/* Enable ADC1 and GPIO clocks ****************************************/
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);

	/* Configure ADC1 Channel10 pin as analogue input ******************************/
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0|GPIO_Pin_1;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AN;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL ;
	GPIO_Init(GPIOA, &GPIO_InitStructure);

	/* ADC Common Init **********************************************************/
	ADC_CommonInitStructure.ADC_Mode = ADC_Mode_Independent;
	ADC_CommonInitStructure.ADC_Prescaler = ADC_Prescaler_Div2;
	ADC_CommonInitStructure.ADC_DMAAccessMode = ADC_DMAAccessMode_Disabled;
	ADC_CommonInitStructure.ADC_TwoSamplingDelay = ADC_TwoSamplingDelay_5Cycles;
	ADC_CommonInit(&ADC_CommonInitStructure);

	/* ADC1 Init ****************************************************************/
	ADC_InitStructure.ADC_Resolution = ADC_Resolution_12b;
	ADC_InitStructure.ADC_ScanConvMode = DISABLE;
	ADC_InitStructure.ADC_ContinuousConvMode = DISABLE;
	ADC_InitStructure.ADC_ExternalTrigConvEdge = ADC_ExternalTrigConvEdge_None;
	ADC_InitStructure.ADC_ExternalTrigConv = DISABLE;
	ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;
	ADC_InitStructure.ADC_NbrOfConversion = 1;
	ADC_Init(ADC1, &ADC_InitStructure);

	/* ADC1 regular channel10 configuration *************************************/
	//ADC_RegularChannelConfig(ADC1, ADC_Channel_2, 1, ADC_SampleTime_3Cycles);
	//ADC_RegularChannelConfig(ADC1, ADC_Channel_3, 1, ADC_SampleTime_3Cycles);
	/* Enable ADC1 */
	ADC_Cmd(ADC1, ENABLE);

}

void DMM_RES_Deint(void){

	// Disable ADC
	ADC_Cmd(ADC1, DISABLE);
	ADC_DeInit();

}

uint16_t ADC1_Read(uint8_t channel){

	ADC_RegularChannelConfig(ADC1,channel, 1, ADC_SampleTime_15Cycles);
	ADC_SoftwareStartConv(ADC1);
	while(!ADC_GetFlagStatus(ADC1,ADC_FLAG_EOC));
	return ADC_GetConversionValue(ADC1);

}

float resisMeasure(void){

	float VB = 0.0f,VD = 0.0f,VG,Rx;
	const int samples = 100;

	/* Step 1: Read Wheatstone bridge voltage*/
    for(int i = 0; i < samples; i++) {
        VB += (ADC1_Read(ADC_Channel_0) * VS) / 4095.0f;
        VD += (ADC1_Read(ADC_Channel_1) * VS) / 4095.0f;
    }

    VB /= samples;
    VD /= samples;
	VG = VB-VD;

	//Rx= (((R2*R3)/(R1+R2))-((VG*R3)/VS))/(1-(R2/(R1+R2))+(VG/VS));

	Rx = ((((VS * R2) - (VG * (R1 + R2))) / ((VS * R1) + (VG * (R1 + R2))))) * R3;

	return 	Rx;

}



/* Temperature Measurement Functions Definition */
void DMM_TEMP_Config(void){

	uint16_t PrescalerValue = 0;

    TIM_TimeBaseInitTypeDef   TIM_TimeBaseStructure;
    TIM_OCInitTypeDef         TIM_OCInitStructure;

    /* TIM2 clock enable */
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);

    TIM_TimeBaseStructInit(&TIM_TimeBaseStructure);
    TIM_OCStructInit(&TIM_OCInitStructure);

    /* Compute the prescaler value */
    PrescalerValue = (uint16_t) (90000000 / 1000000) - 1;

    /* Time base configuration */
    TIM_TimeBaseStructure.TIM_Period = 65535 - 1;      //in uSecs
    TIM_TimeBaseStructure.TIM_Prescaler = PrescalerValue;
    TIM_TimeBaseStructure.TIM_ClockDivision = 0;
    TIM_TimeBaseStructure.TIM_CounterMode = TIM_CounterMode_Up;
    TIM_TimeBaseInit(TIM2, &TIM_TimeBaseStructure);

    TIM_Cmd(TIM2, ENABLE);
}

void DMM_TEMP_Deint(void){

	// Disable TIM2
	TIM_Cmd(TIM2, DISABLE);
	TIM_DeInit(TIM2);
}

/* Capacitance Measurement Functions Definition */
/* Improved Capacitance Measurement Functions Definition */
void DMM_CAP_Config(void){
    GPIO_InitTypeDef GPIO_InitStructure;
    ADC_InitTypeDef ADC_InitStructure;
    ADC_CommonInitTypeDef ADC_CommonInitStructure;
    TIM_TimeBaseInitTypeDef TIM_BaseStruct;

    // Enable clocks
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);

    // Configure PA6 as digital output (charge/discharge control)
    GPIO_InitStructure.GPIO_Pin = CAP_CTRL_PIN;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    // Configure PA7 as analog input (ADC)
    GPIO_InitStructure.GPIO_Pin = CAP_ADC_PIN;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AN;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    // ADC common configuration
    ADC_CommonInitStructure.ADC_Mode = ADC_Mode_Independent;
    ADC_CommonInitStructure.ADC_Prescaler = ADC_Prescaler_Div4;
    ADC_CommonInitStructure.ADC_DMAAccessMode = ADC_DMAAccessMode_Disabled;
    ADC_CommonInitStructure.ADC_TwoSamplingDelay = ADC_TwoSamplingDelay_5Cycles;
    ADC_CommonInit(&ADC_CommonInitStructure);

    // ADC1 configuration
    ADC_InitStructure.ADC_Resolution = ADC_Resolution_12b;
    ADC_InitStructure.ADC_ScanConvMode = DISABLE;
    ADC_InitStructure.ADC_ContinuousConvMode = DISABLE;
    ADC_InitStructure.ADC_ExternalTrigConvEdge = ADC_ExternalTrigConvEdge_None;
    ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;
    ADC_InitStructure.ADC_NbrOfConversion = 1;
    ADC_Init(ADC1, &ADC_InitStructure);

    // Faster sampling time for better response
    ADC_RegularChannelConfig(ADC1, ADC_CHANNEL, 1, ADC_SampleTime_15Cycles);
    ADC_Cmd(ADC1, ENABLE);

    // Timer configuration for microsecond timing (1 MHz timer)
    TIM_BaseStruct.TIM_Prescaler = 84 - 1;  // 84MHz/84 = 1MHz (1µs tick)
    TIM_BaseStruct.TIM_Period = 0xFFFFFFFF;
    TIM_BaseStruct.TIM_CounterMode = TIM_CounterMode_Up;
    TIM_BaseStruct.TIM_ClockDivision = TIM_CKD_DIV1;
    TIM_TimeBaseInit(TIM2, &TIM_BaseStruct);
    TIM_Cmd(TIM2, ENABLE);
}

void DMM_CAP_Deint(void){
    // Disable ADC
    ADC_Cmd(ADC1, DISABLE);
    ADC_DeInit();

    // Disable TIM2
    TIM_Cmd(TIM2, DISABLE);
    TIM_DeInit(TIM2);
}

uint16_t CAP_ADC1_Read(void){
    ADC_SoftwareStartConv(ADC1);
    while (!ADC_GetFlagStatus(ADC1, ADC_FLAG_EOC));
    return ADC_GetConversionValue(ADC1);
}

void Cap_Charge(void){
    GPIO_SetBits(GPIOA, CAP_CTRL_PIN);
}

void Cap_Discharge(void){
    GPIO_ResetBits(GPIOA, CAP_CTRL_PIN);

    // Force ADC pin low to fully discharge capacitor through GPIO
    GPIO_InitTypeDef GPIO_InitStructure;
    GPIO_InitStructure.GPIO_Pin = CAP_ADC_PIN;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_DOWN;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_Init(GPIOA, &GPIO_InitStructure);
    GPIO_ResetBits(GPIOA, CAP_ADC_PIN);

    // Small delay for discharge
    volatile uint32_t i;
    for(i = 0; i < 1000; i++);

    // Reconfigure back to analog mode
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AN;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
    GPIO_Init(GPIOA, &GPIO_InitStructure);
}

// Microsecond delay using TIM2
void CAP_delay_us(uint32_t us) {
    uint32_t start = TIM2->CNT;
    while ((TIM2->CNT - start) < us) {}
}

void ProcessCapacitanceMeasurement(void) {
    static uint32_t last_measurement_time = 0;
    uint32_t current_time = TIM2->CNT;

    // Add debouncing - measure only every 100ms when active
    if (current_time - last_measurement_time < 100000) { // 100ms in microseconds
        return;
    }
    last_measurement_time = current_time;

    switch (capState) {
        case CAP_STATE_DISCHARGED:
            // Force discharge
            Cap_Discharge();
            CAP_delay_us(DISCHARGE_SETTLE_US);

            capState = CAP_STATE_CHARGING;
            cap_start_time = TIM2->CNT;
            break;

        case CAP_STATE_CHARGING:
            // Start charging
            Cap_Charge();

            // Read voltage and check threshold
            uint16_t adc_val = CAP_ADC1_Read();
            uint32_t elapsed_us = TIM2->CNT - cap_start_time;

            if (adc_val >= ADC_THRESHOLD_COUNT) {
                // Voltage reached threshold - calculate capacitance
                float alpha = (float)ADC_THRESHOLD_COUNT / ADC_MAX;
                float k = -logf(1.0f - alpha); // ln(Vs/(Vs-Vth))
                float t_sec = (float)elapsed_us * 1e-6f;

                capacitance_value = t_sec / (RESISTOR * k); // in Farads
                capacitance_value *= 1e6f; // Convert to microfarads

                capState = CAP_STATE_MEASURED;
                cap_measurement_done = 1;

                // Switch to discharge mode
                Cap_Discharge();
            }

            // Timeout protection (5 seconds max)
            if (elapsed_us > TIMEOUT_US) {
                capacitance_value = 0.0f; // Indicate timeout/error
                capState = CAP_STATE_DISCHARGED;
                cap_measurement_done = 1;
                cap_measurement_active = 0;
                Cap_Discharge();
            }
            break;

        case CAP_STATE_MEASURED:
            // Measurement complete, wait for user to exit or restart
            // Small delay before next measurement cycle
            CAP_delay_us(200000); // 200ms delay
            capState = CAP_STATE_DISCHARGED;
            break;
    }
}
/* Connectivity Measurement Functions Definition */
void DMM_CON_Config(void){

	GPIO_InitTypeDef GPIO_InitStructure;

	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB,ENABLE);

	GPIO_InitStructure.GPIO_Pin=GPIO_Pin_0;
	GPIO_InitStructure.GPIO_Mode=GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_OType=GPIO_OType_PP;
	GPIO_InitStructure.GPIO_PuPd=GPIO_PuPd_NOPULL;
	GPIO_InitStructure.GPIO_Speed=GPIO_Speed_50MHz;

	GPIO_Init(GPIOB,&GPIO_InitStructure);

}

void Buzzer_Control(uint8_t state)
{
	if(state)
		GPIO_SetBits(GPIOB,GPIO_Pin_0);
	else
		GPIO_ResetBits(GPIOB,GPIO_Pin_0);
}

/* Voltage Current Measurement Functions Definition */
void DMM_VOL_Config(void){
    ADC_InitTypeDef       ADC_InitStructure;
    ADC_CommonInitTypeDef ADC_CommonInitStructure;
    GPIO_InitTypeDef      GPIO_InitStructure;

    // Enable clocks
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);

    // Configure PA0 (Voltage) and PA1 (Current) as analog inputs
    GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0 | GPIO_Pin_1;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AN;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    // ADC common configuration
    ADC_CommonInitStructure.ADC_Mode = ADC_Mode_Independent;
    ADC_CommonInitStructure.ADC_Prescaler = ADC_Prescaler_Div2;
    ADC_CommonInitStructure.ADC_DMAAccessMode = ADC_DMAAccessMode_Disabled;
    ADC_CommonInitStructure.ADC_TwoSamplingDelay = ADC_TwoSamplingDelay_5Cycles;
    ADC_CommonInit(&ADC_CommonInitStructure);

    // ADC1 configuration
    ADC_InitStructure.ADC_Resolution = ADC_Resolution_12b;
    ADC_InitStructure.ADC_ScanConvMode = DISABLE;
    ADC_InitStructure.ADC_ContinuousConvMode = DISABLE;
    ADC_InitStructure.ADC_ExternalTrigConv = DISABLE;
    ADC_InitStructure.ADC_ExternalTrigConvEdge = ADC_ExternalTrigConvEdge_None;
    ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;
    ADC_InitStructure.ADC_NbrOfConversion = 1;
    ADC_Init(ADC1, &ADC_InitStructure);

    // Enable ADC1
    ADC_Cmd(ADC1, ENABLE);
}

void DMM_VOL_Deint(void){

	// Disable ADC-3
	ADC_Cmd(ADC1, DISABLE);
	ADC_DeInit();
}

void VoltageMeasure(float* Va, float* Vb,float* current_mA){

    *Va = ADC1_Read(ADC_Channel_0); // PA0
    *Vb = ADC1_Read(ADC_Channel_1);	// PA1

    *Va = (*Va * 3.3) / 4095.0;
    *Vb = (*Vb * 3.3) / 4095.0;

    float Rs= 10000.0;
    float current;
    current = (*Va - *Vb)/Rs;

    *current_mA = (current * 1000);

}

